### ISSUE TITLE
Recovery after DB outage is failing

### ISSUE THREAD

**Issue by schumacher-dwpbank** [coditory/sherlock-distributed-lock#79]
In our mission critical microservice system, it is necessary a service recovers from a database restart automatically without having the service itself to be restarted.
Unfortunately, sherlock does not support this.

We are using Postgres as a DB with the latest, JDBC4 compliant driver. 
For example, the Hikari connection pool uses a probe on each connection before it is handed over to the application. 
Sherlock seems to use more low level access to the DB and misses that probe. So after a DB shutdown and restart, it get stuck with invalid connections.

**Comment by pmendelski** [comment]
Hi, thanks for posting this issue.

You're right, there should be an option to pass a connection pool instead of a single connection.
I've just released `v0.4.17` with the fix. [Sample project](https://github.com/coditory/sherlock-distributed-lock/blob/master/sample/src/main/java/com/coditory/sherlock/sample/postgres/PostgresSyncSample.java#L24) is also updated, so it uses with Hikari CP.

**Comment by schumacher-dwpbank** [comment]
Many thanks for the quick fix, Pawel. We'll try that out soon.
